template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "hung1274"
__REPO__ = "lang-hun"
__UND2C__ = "hu"
__UNDEFINED__ = "Hungarian"
__UND__ = "hun"
