template = "https://github.com/giellalt/template-lang-und"
rev_id = 289
template_sha = "599009dae90448ef6fe32b71f7a6880293f3d546"

[replacements]
__GLOTTOLOG_ID__ = "hung1274"
__REPO__ = "lang-hun"
__UND2C__ = "hu"
__UNDEFINED__ = "Hungarian"
__UND__ = "hun"
